"""
Answer component for the Streamlit application.

Responsible for rendering the generated LLM response.
"""

from __future__ import annotations

import streamlit as st


def render_answer(
    answer: str,
) -> None:
    """
    Render the assistant response.

    Parameters
    ----------
    answer:
        Response generated by the RAG pipeline.
    """

    st.markdown(answer)