"""
Builder for the BM25 lexical index.

Builds a BM25-compatible corpus from document chunks.
"""

from __future__ import annotations

from src.chunking.models import Chunk
from src.indexing.bm25_models import BM25IndexData


class BM25IndexBuilder:
    """
    Builds the lexical corpus required for BM25 retrieval.
    """

    def build(
        self,
        chunks: list[Chunk],
    ) -> BM25IndexData:
        """
        Build a BM25 index from document chunks.

        Parameters
        ----------
        chunks:
            Chunked documents generated by the chunking pipeline.

        Returns
        -------
        BM25IndexData
            BM25 lexical corpus.
        """

        tokenized_documents: list[list[str]] = []
        documents: list[str] = []
        chunk_ids: list[str] = []
        metadatas: list[dict] = []

        for chunk in chunks:

            documents.append(
                chunk.text,
            )

            tokenized_documents.append(
                self._tokenize(
                    chunk.text,
                )
            )

            chunk_ids.append(
                chunk.id,
            )

            metadatas.append(
                chunk.metadata,
            )

        return BM25IndexData(
            tokenized_documents=tokenized_documents,
            documents=documents,
            chunk_ids=chunk_ids,
            metadatas=metadatas,
        )

    @staticmethod
    def _tokenize(
        text: str,
    ) -> list[str]:
        """
        Tokenize a document for BM25 indexing.

        Parameters
        ----------
        text:
            Document text.

        Returns
        -------
        list[str]
            Lower-cased whitespace tokens.
        """

        return text.lower().split()