"""
Build embedding-ready chunks from rich product documents.
"""

from __future__ import annotations

import logging

from src.document_builder.models import Document

from .models import Chunk
from .splitter import (
    split_document,
    DEFAULT_CHUNK_SIZE,
    DEFAULT_OVERLAP,
)

logger = logging.getLogger(__name__)


def build_chunks(
    documents: list[Document],
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    overlap: int = DEFAULT_OVERLAP,
) -> list[Chunk]:
    """
    Generate embedding-ready chunks from rich product documents.

    Parameters
    ----------
    documents:
        Rich documents generated by the Document Builder.

    Returns
    -------
    list[Chunk]
        Chunk objects ready for embedding generation.
    """

    logger.info(
        "Starting chunk generation for %d documents.",
        len(documents),
    )

    chunks: list[Chunk] = []

    try:

        for document in documents:

            chunk_texts = split_document(
                document.text,
                chunk_size=chunk_size,
                overlap=overlap,
            )

            for chunk_index, chunk_text in enumerate(chunk_texts):

                chunk_id = (
                    f"{document.id}_chunk_{chunk_index:03d}"
                )

                metadata = document.metadata.copy()

                metadata["chunk_index"] = chunk_index
                metadata["chunk_id"] = chunk_id

                chunks.append(
                    Chunk(
                        id=chunk_id,
                        text=chunk_text,
                        metadata=metadata,
                    )
                )

        logger.info(
            "Successfully generated %d chunks.",
            len(chunks),
        )

        return chunks

    except Exception:

        logger.exception(
            "Chunk generation failed."
        )

        raise