"""
Utilities for splitting rich product documents into embedding-ready chunks.

The splitter preserves semantic document sections whenever possible and
uses the embedding model's tokenizer to generate token-aware chunks.
"""

from __future__ import annotations

import re

from transformers import AutoTokenizer


# ---------------------------------------------------------------------
# Chunking configuration
# ---------------------------------------------------------------------

EMBEDDING_MODEL = "BAAI/bge-small-en-v1.5"

DEFAULT_CHUNK_SIZE = 384
DEFAULT_OVERLAP = 64


# ---------------------------------------------------------------------
# Tokenizer
# ---------------------------------------------------------------------

tokenizer = AutoTokenizer.from_pretrained(EMBEDDING_MODEL)


# ---------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------

def split_document(
    document_text: str,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    overlap: int = DEFAULT_OVERLAP,
) -> list[str]:
    """
    Split a rich product document into token-aware chunks.

    The document is first divided into semantic sections. Each section is
    then split using the embedding model tokenizer if it exceeds the
    configured chunk size.

    Parameters
    ----------
    document_text:
        Rich product document generated by the Document Builder.

    chunk_size:
        Maximum number of tokens per chunk.

    overlap:
        Number of overlapping tokens between consecutive chunks.

    Returns
    -------
    list[str]
        Embedding-ready text chunks.
    """

    chunks: list[str] = []

    sections = _extract_sections(document_text)

    for section in sections:
        chunks.extend(
            _split_tokens(
                section,
                chunk_size=chunk_size,
                overlap=overlap,
            )
        )

    return chunks


# ---------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------

def _extract_sections(document_text: str) -> list[str]:
    """
    Split a rich product document into semantic sections.

    Returns one string per section while preserving the section heading.
    """

    pattern = (
        r"=+\n"
        r"(PRODUCT INFORMATION|ABOUT THIS ITEM|CUSTOMER REVIEWS)\n"
        r"=+\n"
    )

    matches = list(
        re.finditer(
            pattern,
            document_text,
            flags=re.MULTILINE,
        )
    )

    if not matches:
        return [document_text.strip()]

    sections: list[str] = []

    for i, match in enumerate(matches):

        start = match.start()

        if i + 1 < len(matches):
            end = matches[i + 1].start()
        else:
            end = len(document_text)

        sections.append(document_text[start:end].strip())

    return sections


def _split_tokens(
    text: str,
    chunk_size: int,
    overlap: int,
) -> list[str]:
    """
    Split text into overlapping token chunks using the embedding tokenizer.
    """

    token_ids = tokenizer(
                    text,
                    add_special_tokens=False,
                    truncation=False,
)["input_ids"]

    if len(token_ids) <= chunk_size:
        return [text]

    chunks: list[str] = []

    step = chunk_size - overlap

    for start in range(0, len(token_ids), step):

        end = start + chunk_size

        chunk_ids = token_ids[start:end]

        if not chunk_ids:
            break

        chunks.append(
            tokenizer.decode(
                chunk_ids,
                skip_special_tokens=True,
            ).strip()
        )

        if end >= len(token_ids):
            break

    return chunks